/* Copyright (c) 2005 Agorics; see MIT_License in this directory
or http://www.opensource.org/licenses/mit-license.html */

/*****************************************************************************
  DON'T USE THIS IN ANY NEW OBJECTS 
  REMOVE THIS IN OLD OBJECTS AS SOON AS POSSIBLE
*****************************************************************************/
/* Please use PLIH to maintain this file */
#define WOMB_FACIL 0
#define womb_facil 0
#define WOMB_FACIL_FUND 0
#define womb_facil_fund 0
#define WOMB_FACIL_FUND_DISCRIM 0
#define womb_facil_fund_discrim 0
#define WOMB_FACIL_FUND_DKC 1
#define womb_facil_fund_dkc 1
#define WOMB_FACIL_FUND_RETR 2
#define womb_facil_fund_retr 2
#define WOMB_FACIL_FUND_SBT 4
#define womb_facil_fund_sbt 4
#define WOMB_FACIL_FUND_FACTORYC 5
#define womb_facil_fund_factoryc 5
#define WOMB_FACIL_FUND_DAT2INST 7
#define womb_facil_fund_dat2inst 7
#define WOMB_FACIL_SUPP 1
#define womb_facil_supp 1
#define WOMB_FACIL_SUPP_DCC 0
#define womb_facil_supp_dcc 0
#define WOMB_FACIL_SUPP_SNC 1
#define womb_facil_supp_snc 1
#define WOMB_FACIL_SUPP_FSC 2
#define womb_facil_supp_fsc 2
#define WOMB_FACIL_SUPP_NEVER 4
#define womb_facil_supp_never 4
#define WOMB_FACIL_SUPP_TSSC 5
#define womb_facil_supp_tssc 5
#define WOMB_FACIL_SUPP_VDK2RCF 6
#define womb_facil_supp_vdk2rcf 6
#define WOMB_FACIL_SUPP_SWITCHC 7
#define womb_facil_supp_switchc 7
#define WOMB_FACIL_SUPP_VDKC 8
#define womb_facil_supp_vdkc 8
#define WOMB_FACIL_SUPP_RCC 9
#define womb_facil_supp_rcc 9
#define WOMB_FACIL_SUPP_CLOCK 10
#define womb_facil_supp_clock 10
#define WOMB_FACIL_SUPP_CALLSEGF 11
#define womb_facil_supp_callsegf 11
#define WOMB_FACIL_SUPP_BSLOAD 12
#define womb_facil_supp_bsload 12
#define WOMB_FACIL_SUPP_VCSK 14
#define womb_facil_supp_vcsk 14
#define WOMB_FACIL_SUPP_PDDTC 15
#define womb_facil_supp_pddtc 15
#define WOMB_FACIL_SUPP_BSTSCC 16
#define womb_facil_supp_bstscc 16
#define WOMB_FACIL_SUPP_STRCCC 17
#define womb_facil_supp_strccc 17
#define WOMB_FACIL_SUPP_BSCR 18
#define womb_facil_supp_bscr 18
#define WOMB_FACIL_SUPP_PCSKEEPF 20
#define womb_facil_supp_pcskeepf 20
#define WOMB_FACIL_SUPP_PCSF 22
#define womb_facil_supp_pcsf 22
#define WOMB_FACIL_SUPP_PROTCC 23
#define womb_facil_supp_protcc 23
#define WOMB_FACIL_SUPP_MBWAIT2F 24
#define womb_facil_supp_mbwait2f 24
#define WOMB_FACIL_SUPP_BSLOADF 28
#define womb_facil_supp_bsloadf 28
#define WOMB_FACIL_SUPP_EDITF 29
#define womb_facil_supp_editf 29
#define WOMB_FACIL_SUPP_DDTF 30
#define womb_facil_supp_ddtf 30
#define WOMB_FACIL_SUPP_BINDF 31
#define womb_facil_supp_bindf 31
#define WOMB_FACIL_SUPP_OSSIMF 32
#define womb_facil_supp_ossimf 32
#define WOMB_FACIL_SUPP_REGISTRYC 33
#define womb_facil_supp_registryc 33
#define WOMB_FACIL_SUPP_MKEEPERC 34
#define womb_facil_supp_mkeeperc 34
#define WOMB_FACIL_SUPP_GNFDEF 35
#define womb_facil_supp_gnfdef 35
#define WOMB_FACIL_SUPP_ADDLUDKY 36
#define womb_facil_supp_addludky 36
#define WOMB_FACIL_SUPP_SIAF 37
#define womb_facil_supp_siaf 37
#define WOMB_FACIL_SUPP_CSWITCHC 38
#define womb_facil_supp_cswitchc 38
/* 40 - OLD callsegf */
#define WOMB_FACIL_SUPP_TAPE2OBJF 41
#define womb_facil_supp_tape2objf 41
#define WOMB_FACIL_SUPP_RESTOREF 42
#define womb_facil_supp_restoref 42
#define WOMB_FACIL_SUPP_ACCESSF 43
#define womb_facil_supp_accessf 43
 /* 44 unused */
#define WOMB_FACIL_SUPP_R3270F 45
#define womb_facil_supp_r3270f 45
#define WOMB_FACIL_SUPP_GNFORMF 46
#define womb_facil_supp_gnformf 46
#define WOMB_FACIL_SUPP_READCRDF 47
#define womb_facil_supp_readcrdf 47
#define WOMB_FACIL_SUPP_TAPEDVRF 48
#define womb_facil_supp_tapedvrf 48
#define WOMB_FACIL_SUPP_JOINF 49
#define womb_facil_supp_joinf 49
#define WOMB_FACIL_SUPP_METMONF 50
#define womb_facil_supp_metmonf 50
#define WOMB_FACIL_SUPP_TERMFEF 51
#define womb_facil_supp_termfef 51
#define WOMB_FACIL_SUPP_PFORKF 52
#define womb_facil_supp_pforkf 52
#define WOMB_FACIL_SUPP_NOTIFMF 53
#define womb_facil_supp_notifmf 53
#define WOMB_FACIL_SUPP_SYSKEYS2F 54
#define womb_facil_supp_syskeys2f 54
#define WOMB_FACIL_SUPP_WAITF 55
#define womb_facil_supp_waitf 55
#define WOMB_FACIL_SUPP_TYPE 56
#define womb_facil_supp_type 56
#define WOMB_FACIL_SUPP_KEYDEVF 57
#define womb_facil_supp_keydevf 57
#define WOMB_FACIL_SUPP_KEYJOINF 58
#define womb_facil_supp_keyjoinf 58
#define WOMB_FACIL_SUPP_BRKDOMF 59
#define womb_facil_supp_brkdomf 59
#define WOMB_FACIL_SUPP_CONFIGF 60
#define womb_facil_supp_configf 60
#define WOMB_FACIL_SUPP_FORKF 61
#define womb_facil_supp_forkf 61
#define womb_facil_supp_sik2sim 62
#define WOMB_FACIL_SUPP_SIK2SIM 62
#define womb_facil_supp_cmnerrf 63
#define WOMB_FACIL_SUPP_CMNERRF 63
#define womb_facil_supp_datacopy 64
#define WOMB_FACIL_SUPP_DATACOPY 64
#define womb_facil_supp_snode2 65
#define WOMB_FACIL_SUPP_SNODE2 65
#define womb_facil_supp_vkdf 66
#define WOMB_FACIL_SUPP_VDKF 66



#define WOMB_FACIL_RES 2
#define womb_facil_res 2
#define WOMB_FACIL_RES_METER 0
#define womb_facil_res_meter 0
#define WOMB_FACIL_RES_SB 1
#define womb_facil_res_sb 1
#define WOMB_FACIL_RES_DOMKEEP 2
#define womb_facil_res_domkeep 2
#define WOMB_FACIL_BOOT 3
#define womb_facil_boot 3
#define WOMB_FACIL_RES_MBWAIT2 5
#define womb_facil_res_mbwait2 5
#define WOMB_FACIL_RES_MBWAIT2DOM 6
#define womb_facil_res_mbwait2dom 6
#define WOMB_MEM 1
#define womb_mem 1
#define WOMB_CALLER 2
#define womb_caller 2
#define WOMB_DOMKEY 3
#define womb_domkey 3
 /* The following are for Solaris demo */
