/* Please use PLIH to maintain this file */
#define CONCCK__WAIT_FOR_CONNECT 0
#define concck__wait_for_connect 0
#define CONCCK__SET_BACKPRESSURE 1
#define concck__set_backpressure 1
#define CONCCK__SEND_ZAP 2
#define concck__send_zap 2
#define CONCCK__START_GOBBLING 3
#define concck__start_gobbling 3
#define CONCCK__WAIT_FOR_ZAP 4
#define concck__wait_for_zap 4
#define CONCCK__ACTIVATE_NOW 6
#define concck__activate_now 6
#define CONCCK__STOP_GOBBLING 7
#define concck__stop_gobbling 7
#define CONCCK__CR_AS_CRLF 8
#define concck__cr_as_crlf 8
#define CONCCK__CR_AS_CR 9
#define concck__cr_as_cr 9
#define CONCCK__LF_AS_LFCR 10
#define concck__lf_as_lfcr 10
#define CONCCK__LF_AS_LF 11
#define concck__lf_as_lf 11
#define CONCCK__SET_ACTIVATION_SET 30
#define concck__set_activation_set 30
#define CONCCK__SET_ECHO_SET 31
#define concck__set_echo_set 31
#define CONCCK__START_LOG 32
#define concck__start_log 32
#define CONCCK__START_BUFFERED_LOG  33
#define concck__start_buffered_log  33
#define CONCCK__STOP_LOG 34
#define concck__stop_log 34
#define CONCCK__PRINT_LOG 35
#define CONCCK__print_log 35
