/* Please use PLIH to maintain this file */
#define DOMAIN__GET 0
#define domain__get 0
#define DOMAIN__GET_KEY 16
#define domain__get_key 16
#define DOMAIN__SWAP 32
#define domain__swap 32
#define DOMAIN__SWAP_KEY 48
#define domain__swap_key 48
#define DOMAIN__CREATE_ENTRY 64
#define domain__create_entry 64
#define DOMAIN__MAKE_START 64
#define domain__make_start 64
#define DOMAIN__MAKE_READY 65
#define domain__make_ready 65
#define DOMAIN__MAKE_AVAILABLE 65
#define domain__make_available 65
#define DOMAIN__CREATE_FAULT_EXIT 66
#define domain__create_fault_exit 66
#define DOMAIN__MAKE_FAULT_EXIT 66
#define domain__make_fault_exit 66
#define DOMAIN__MAKE_FAULT 66
#define domain__make_fault 66
#define DOMAIN__MAKE_BUSY 67
#define domain__make_busy 67
#define DOMAIN__GET_CONTROL 68
#define domain__get_control 68
#define DOMAIN__PUT_CONTROL 69
#define domain__put_control 69
#define DOMAIN__GET_REGS 70
#define domain__get_regs 70
#define DOMAIN__PUT_REGS 71
#define domain__put_regs 71
#define DOMAIN__WEAKEN 72
#define domain__weaken 72
#define DOMAIN__CREATE_RETURN_EXIT 73
#define domain__create_return_exit 73
#define DOMAIN__MAKE_RETURN_EXIT 73
#define domain__make_return_exit 73
#define DOMAIN__MAKE_RETURN 73
#define domain__make_return 73
#define DOMAIN__REPLACE_MEMORY 74
#define domain__replace_memory 74
#define DOMAIN__PUT_STUFF 75
#define domain__put_stuff 75
#define DOMAIN__COMPARE 80
#define domain__compare 80
