kc user/sys/bsloadf 0 (,sb,m,sb) (,bsload)
kc user/sys/vcsf 0 (,sb,m,sb) (,prgj)
kc bsload 0 (,test/join,prgj) (sa)
kc prgj 17 (,sb)  (,prgfacj)
kc user/sys/factoryc 0 (,sb,m) (,fbj)
kc fbj 17+32 (sa,prgfacj)
kc fbj 66 () (,joinf)

kc user/sys/vcsf 0 (,sb,m,sb) (,prgf)
kc bsload 0 (,test/Lorentz,prgf) (sa)
kc prgf 17 (,sb)  (,prgfacf)
kc user/sys/factoryc 0 (,sb,m) (,fbf)
kc fbf 17+32 (sa,prgfacf)
kc fbf 66 () (,ff)

kc joinf 40 (,sb,m,sb) (,j1s,,,j1r)
kc joinf 40 (,sb,m,sb) (,j2s,,,j2r)
kc joinf 40 (,sb,m,sb) (,j3s,,,j3r)
kfork ff 1 (,sb,m,sb,j1r)
kfork ff 2 (,sb,m,sb,j2r)
kfork ff 3 (,sb,m,sb,j3r)

kc j1s 1 () (%x)
kc j2s 1 () (%x)
kc j3s 1 () (%x)
